"""Auto-generate soccer tables

Revision ID: 6a639c5fd25e
Revises: 
Create Date: 2026-01-26 12:54:04.868407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a639c5fd25e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('team_code', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('e_player_name', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('join_yyyy', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('back_no', sa.Integer(), nullable=True),
    sa.Column('nation', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('solar', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stadium_id', sa.BigInteger(), nullable=True),
    sa.Column('hometeam_id', sa.BigInteger(), nullable=True),
    sa.Column('awayteam_id', sa.BigInteger(), nullable=True),
    sa.Column('stadium_code', sa.String(), nullable=False),
    sa.Column('sche_date', sa.String(), nullable=False),
    sa.Column('gubun', sa.String(), nullable=False),
    sa.Column('hometeam_code', sa.String(), nullable=False),
    sa.Column('awayteam_code', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stadium',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stadium_code', sa.String(), nullable=False),
    sa.Column('statdium_name', sa.String(), nullable=False),
    sa.Column('hometeam_code', sa.String(), nullable=True),
    sa.Column('seat_count', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('ddd', sa.String(), nullable=True),
    sa.Column('tel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stadium_id', sa.BigInteger(), nullable=True),
    sa.Column('team_code', sa.String(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('e_team_name', sa.String(), nullable=True),
    sa.Column('orig_yyyy', sa.String(), nullable=True),
    sa.Column('stadium_code', sa.String(), nullable=True),
    sa.Column('zip_code1', sa.String(), nullable=True),
    sa.Column('zip_code2', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('ddd', sa.String(), nullable=True),
    sa.Column('tel', sa.String(), nullable=True),
    sa.Column('fax', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('langchain_pg_embedding')
    op.drop_table('gri_standards')
    op.drop_table('langchain_pg_collection')
    op.drop_table('users')
    op.drop_index(op.f('idx_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('ukghpmfn23vmxfu3spu3lfg4r2d'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('uk7tdcd6ab5wsgoudnvj7xf1b7l'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('oauth_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('oauth_provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('profile_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.CheckConstraint("oauth_provider::text = ANY (ARRAY['KAKAO'::character varying, 'NAVER'::character varying, 'GOOGLE'::character varying]::text[])", name=op.f('users_oauth_provider_check')),
    sa.CheckConstraint("role::text = ANY (ARRAY['USER'::character varying, 'ADMIN'::character varying]::text[])", name=op.f('users_role_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('uk6dotkott2kjsp8vw4d0m25fb7'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('oauth_provider', 'oauth_id', name=op.f('uk94v11ixih73new14vukvmfkjl'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('langchain_pg_collection',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_collection_pkey'))
    )
    op.create_table('gri_standards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('standard_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('standard_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('published_year', sa.INTEGER(), server_default=sa.text('2021'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gri_standards_pkey')),
    sa.UniqueConstraint('standard_code', name=op.f('gri_standards_standard_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('langchain_pg_embedding',
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('custom_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_embedding_pkey'))
    )
    op.drop_table('team')
    op.drop_table('stadium')
    op.drop_table('schedule')
    op.drop_table('player')
    # ### end Alembic commands ###
