"""Auto-generate soccer tables

Revision ID: a0a634b9a9c9
Revises: 4bda59a7da7e
Create Date: 2026-01-26 12:55:33.142854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a634b9a9c9'
down_revision: Union[str, None] = '4bda59a7da7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
