"""Auto-generate soccer tables

Revision ID: b7cfdfc37c57
Revises: a0a634b9a9c9
Create Date: 2026-01-26 12:55:49.503044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7cfdfc37c57'
down_revision: Union[str, None] = 'a0a634b9a9c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
