"""Auto-generate soccer tables

Revision ID: dcd06a6b8416
Revises: b7cfdfc37c57
Create Date: 2026-01-26 12:56:06.745548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd06a6b8416'
down_revision: Union[str, None] = 'b7cfdfc37c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
